### ISSUE TITLE
Add me

### ISSUE THREAD

**Issue by githubstudent** [stoe/issue-colab-test#2]

**Comment by stoe** [comment]
:tada: @githubstudent you are now a repository collaborator. :balloon:

**Comment by stoe** [comment]
:tada: @githubstudent you are now a repository collaborator. :balloon:

**Comment by stoe** [comment]
:tada: @githubstudent you are now a repository collaborator. :balloon:

**Comment by stoe** [comment]
:tada: @githubstudent you are now a repository collaborator. :balloon:

**Comment by stoe** [comment]
foobar

**Comment by stoe** [comment]
foobar
